services:
  - type: web
    name: devgap-ai-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GITHUB_TOKEN
        sync: false
      - key: FRONTEND_URL
        value: https://charusat-project.netlify.app
